---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/${MOLECULE_DISTRO:-'debian:10'}
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
