name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: 'stonesoupkitchen.sudo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'stonesoupkitchen.sudo'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ansible-lint
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ansible-lint

      - name: Lint with ansible-lint and generate Code Climate report
        if: ${{ github.event_name == 'push' }}
        run: |
          ansible-lint -f codeclimate | tee ansiblelint.json

      - name: Publish Code Climate report
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -LJ https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
          chmod +x cc-test-reporter
          ./cc-test-reporter upload-coverage --input ansiblelint.json --id ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Run Molecule tests
        run: molecule test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
